// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetAPI.Migrations
{
    [DbContext(typeof(ITAssetDbContext))]
    partial class ITAssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Building", b =>
                {
                    b.Property<int>("BuildingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingID"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<int>("EquipmentBrandID")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentStatusID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentTypeID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("OtherIDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentID");

                    b.HasIndex("EquipmentBrandID");

                    b.HasIndex("EquipmentStatusID");

                    b.HasIndex("EquipmentTypeID");

                    b.HasIndex("LocationID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EquipmentBrand", b =>
                {
                    b.Property<int>("EquipmentBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentBrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentBrandID");

                    b.ToTable("EquipmentBrands");

                    b.HasData(
                        new
                        {
                            EquipmentBrandID = 1,
                            BrandName = "Dell"
                        },
                        new
                        {
                            EquipmentBrandID = 2,
                            BrandName = "HP"
                        },
                        new
                        {
                            EquipmentBrandID = 3,
                            BrandName = "Lenovo"
                        },
                        new
                        {
                            EquipmentBrandID = 4,
                            BrandName = "Apple"
                        },
                        new
                        {
                            EquipmentBrandID = 5,
                            BrandName = "ClearTouch"
                        },
                        new
                        {
                            EquipmentBrandID = 6,
                            BrandName = "Poly"
                        },
                        new
                        {
                            EquipmentBrandID = 7,
                            BrandName = "Bizhub"
                        },
                        new
                        {
                            EquipmentBrandID = 8,
                            BrandName = "Kyocera"
                        });
                });

            modelBuilder.Entity("EquipmentStatus", b =>
                {
                    b.Property<int>("EquipmentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentStatusID"));

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentStatusID");

                    b.ToTable("EquipmentStatuses");

                    b.HasData(
                        new
                        {
                            EquipmentStatusID = 1,
                            StatusDescription = "In use and operational",
                            StatusName = "Active"
                        },
                        new
                        {
                            EquipmentStatusID = 2,
                            StatusDescription = "Currently being serviced",
                            StatusName = "In Repair"
                        },
                        new
                        {
                            EquipmentStatusID = 3,
                            StatusDescription = "Not deployed",
                            StatusName = "In Storage"
                        },
                        new
                        {
                            EquipmentStatusID = 4,
                            StatusDescription = "End of life",
                            StatusName = "Retired"
                        },
                        new
                        {
                            EquipmentStatusID = 5,
                            StatusDescription = "Location unknown",
                            StatusName = "Missing"
                        });
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentTypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentTypeID");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            EquipmentTypeID = 1,
                            TypeName = "Desktop"
                        },
                        new
                        {
                            EquipmentTypeID = 2,
                            TypeName = "Laptop"
                        },
                        new
                        {
                            EquipmentTypeID = 3,
                            TypeName = "All-in-One"
                        },
                        new
                        {
                            EquipmentTypeID = 4,
                            TypeName = "Printer"
                        },
                        new
                        {
                            EquipmentTypeID = 5,
                            TypeName = "Interactive Display"
                        },
                        new
                        {
                            EquipmentTypeID = 6,
                            TypeName = "Phone"
                        },
                        new
                        {
                            EquipmentTypeID = 7,
                            TypeName = "Monitor"
                        },
                        new
                        {
                            EquipmentTypeID = 8,
                            TypeName = "PC Module"
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<int>("BuildingID")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("BuildingID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("RoomTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            RoomTypeDescription = "Classroom"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            RoomTypeDescription = "Computer Lab"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            RoomTypeDescription = "Faculty Office"
                        },
                        new
                        {
                            RoomTypeID = 4,
                            RoomTypeDescription = "Staff Office"
                        },
                        new
                        {
                            RoomTypeID = 5,
                            RoomTypeDescription = "Conference Room"
                        },
                        new
                        {
                            RoomTypeID = 6,
                            RoomTypeDescription = "Storage"
                        },
                        new
                        {
                            RoomTypeID = 7,
                            RoomTypeDescription = "IT"
                        });
                });

            modelBuilder.Entity("Equipment", b =>
                {
                    b.HasOne("EquipmentBrand", "EquipmentBrand")
                        .WithMany()
                        .HasForeignKey("EquipmentBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentStatus", "EquipmentStatus")
                        .WithMany()
                        .HasForeignKey("EquipmentStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentBrand");

                    b.Navigation("EquipmentStatus");

                    b.Navigation("EquipmentType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.HasOne("Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("RoomType");
                });
#pragma warning restore 612, 618
        }
    }
}
